name: Run SteamMD Generator

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  generate-steammd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SteamMD Action
        uses: doctor-versum/SteamMD@v0.1.3
        with:
          steam_api_key: ${{ secrets.STEAM_TOKEN }}
          steam_vanity_url: doctor-versum

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git pull
          git add .
          git commit -m "Auto-update: SteamMD output" || echo "No changes to commit"
          git push
