name: Fetch External GitHub Widgets

on:
  schedule:
    - cron: '0 * * * *'  # Jede Stunde
  workflow_dispatch:

jobs:
  fetch-widgets:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # erlaubt Pushes ins Repo
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download GitHub Widgets
        run: |
          mkdir -p generated/readme-stats

          # Contribution Graph (hell/dunkel)
          curl -sL "https://github-readme-activity-graph.vercel.app/graph?username=doctor-versum&bg_color=ffffff00&color=000000&line=9e4c98&point=000000&area=true&hide_border=true&radius=30" -o generated/readme-stats/contributions-light.svg
          curl -sL "https://github-readme-activity-graph.vercel.app/graph?username=doctor-versum&bg_color=ffffff00&color=ffffff&line=9e4c98&point=ffffff&area=true&hide_border=true&radius=30" -o generated/readme-stats/contributions-dark.svg

          mkdir -p generated/langs

          # Top Languages
          curl -sL "https://github-readme-stats.vercel.app/api/top-langs?username=doctor-versum&layout=compact&theme=default" -o generated/langs/langs-light.svg
          curl -sL "https://github-readme-stats.vercel.app/api/top-langs?username=doctor-versum&layout=compact&theme=dark" -o generated/langs/langs-dark.svg

          mkdir -p generated/streaks

          # GitHub Streaks (optional)
          curl -sL "https://github-readme-streak-stats.herokuapp.com/?user=doctor-versum&theme=default" -o generated/streaks/streaks-light.svg
          curl -sL "https://github-readme-streak-stats.herokuapp.com/?user=doctor-versum&theme=dark" -o generated/streaks/streaks-dark.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add generated/*/*
          git commit -m "chore: update external GitHub widgets" || echo "No changes"
          git push